

GOOGLE_API_KEY = "AIzaSyDNimkKNt1umTFbPni6CGt0t071wy2yhz8"

# If you want to use Infermedica free symptom checker API, add these keys
INFERMEDICA_APP_ID = "your_infermedica_app_id_here"
INFERMEDICA_APP_KEY = "your_infermedica_app_key_here"

SUPABASE_URL = "https://zmjzsbsefukaqetnwfuj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptanpzYnNlZnVrYXFldG53ZnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTA0OTUsImV4cCI6MjA3MzgyNjQ5NX0.Zh2gldYWK_6pXBX0jXHkaT9ouK50KGXk4Ib71SP_in4"
GEMINI_API_KEY = "AIzaSyAHdcnrdebWOzgYrVE_1LwxX5Ji4MmbGeE"
